/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaToC_MIPSolverC */

#ifndef _Included_javaToC_MIPSolverC
#define _Included_javaToC_MIPSolverC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaToC_MIPSolverC
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaToC_MIPSolverC_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     javaToC_MIPSolverC
 * Method:    solveMIP
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;IZ)J
 */
JNIEXPORT jlong JNICALL Java_javaToC_MIPSolverC_solveMIP
  (JNIEnv *, jobject, jobject, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
